import camperaDenimImg from '../recursos/imagenes/modelo_jean.webp'
import jeansMujerImg from '../recursos/imagenes/modelo_mujer.webp'
import remeraBasicaImg from '../recursos/imagenes/modelo_hombre.webp'
import vestidoMidiImg from '../recursos/imagenes/modelo_mujerApaisada.webp'
import buzoUrbanoImg from '../recursos/imagenes/modelo_hombreApaisada.webp'
import accesoriosImg from '../recursos/imagenes/accesorios.webp'

export const productos = [
  {
    id: 'prod-remera-basica',
    nombre: 'Remera basica',
    slug: 'remera-basica',
    marca: 'Vestidor',
    genero: 'hombre',
    categorias: ['remeras'],
    imagenes: [{ src: remeraBasicaImg, alt: 'Remera basica' }],
    variantes: [
      {
        id: 'var-remera-negro-m',
        barcode: '779001',
        color: 'Negro',
        talle: 'M',
        precio: 18900,
        stockDisponible: 10,
        activo: true,
      },
      {
        id: 'var-remera-blanco-l',
        barcode: '779005',
        color: 'Blanco',
        talle: 'L',
        precio: 18900,
        stockDisponible: 3,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-jean-mom',
    nombre: 'Jean mom',
    slug: 'jean-mom',
    marca: 'Urbana',
    genero: 'mujer',
    categorias: ['jeans'],
    imagenes: [{ src: jeansMujerImg, alt: 'Jean mom' }],
    variantes: [
      {
        id: 'var-jean-azul-40',
        barcode: '779002',
        color: 'Azul',
        talle: '40',
        precio: 42500,
        stockDisponible: 3,
        activo: true,
      },
      {
        id: 'var-jean-negro-42',
        barcode: '779006',
        color: 'Negro',
        talle: '42',
        precio: 42500,
        stockDisponible: 0,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-jean-wide-leg',
    nombre: 'Jean wide leg',
    slug: 'jean-wide-leg',
    marca: 'Levis',
    genero: 'mujer',
    categorias: ['jeans'],
    imagenes: [{ src: vestidoMidiImg, alt: 'Jean wide leg' }],
    variantes: [
      {
        id: 'var-jean-wide-azul-38',
        barcode: '779009',
        color: 'Azul',
        talle: '38',
        precio: 48900,
        stockDisponible: 6,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-jean-skinny',
    nombre: 'Jean skinny',
    slug: 'jean-skinny',
    marca: 'Urbana',
    genero: 'mujer',
    categorias: ['jeans'],
    imagenes: [{ src: jeansMujerImg, alt: 'Jean skinny' }],
    variantes: [
      {
        id: 'var-jean-skinny-negro-40',
        barcode: '779010',
        color: 'Negro',
        talle: '40',
        precio: 39900,
        stockDisponible: 4,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-jean-recto',
    nombre: 'Jean recto',
    slug: 'jean-recto',
    marca: 'Aura',
    genero: 'mujer',
    categorias: ['jeans'],
    imagenes: [{ src: vestidoMidiImg, alt: 'Jean recto' }],
    variantes: [
      {
        id: 'var-jean-recto-celeste-42',
        barcode: '779011',
        color: 'Celeste',
        talle: '42',
        precio: 45900,
        stockDisponible: 7,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-jean-oxford',
    nombre: 'Jean oxford',
    slug: 'jean-oxford',
    marca: 'Norte',
    genero: 'mujer',
    categorias: ['jeans'],
    imagenes: [{ src: jeansMujerImg, alt: 'Jean oxford' }],
    variantes: [
      {
        id: 'var-jean-oxford-azul-36',
        barcode: '779012',
        color: 'Azul',
        talle: '36',
        precio: 46900,
        stockDisponible: 5,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-campera-denim',
    nombre: 'Campera denim',
    slug: 'campera-denim',
    marca: 'Norte',
    genero: 'mujer',
    categorias: ['camperas'],
    imagenes: [{ src: camperaDenimImg, alt: 'Campera denim' }],
    variantes: [
      {
        id: 'var-campera-celeste-l',
        barcode: '779003',
        color: 'Celeste',
        talle: 'L',
        precio: 69900,
        stockDisponible: 0,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-camisa-lino',
    nombre: 'Camisa lino',
    slug: 'camisa-lino',
    marca: 'Vestidor',
    genero: 'mujer',
    categorias: ['camisas'],
    imagenes: [{ src: vestidoMidiImg, alt: 'Camisa de lino' }],
    variantes: [
      {
        id: 'var-camisa-lino-blanco-m',
        barcode: '779013',
        color: 'Blanco',
        talle: 'M',
        precio: 32900,
        stockDisponible: 6,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-remera-mujer',
    nombre: 'Remera rib',
    slug: 'remera-rib',
    marca: 'Aura',
    genero: 'mujer',
    categorias: ['remeras'],
    imagenes: [{ src: vestidoMidiImg, alt: 'Remera rib' }],
    variantes: [
      {
        id: 'var-remera-rib-negro-s',
        barcode: '779014',
        color: 'Negro',
        talle: 'S',
        precio: 21900,
        stockDisponible: 9,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-vestido-midi',
    nombre: 'Vestido midi',
    slug: 'vestido-midi',
    marca: 'Aura',
    genero: 'mujer',
    categorias: ['faldas-y-vestidos'],
    imagenes: [{ src: vestidoMidiImg, alt: 'Vestido midi' }],
    variantes: [
      {
        id: 'var-vestido-rojo-s',
        barcode: '779004',
        color: 'Rojo',
        talle: 'S',
        precio: 37200,
        stockDisponible: 5,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-bermuda-denim',
    nombre: 'Bermuda denim',
    slug: 'bermuda-denim',
    marca: 'Norte',
    genero: 'hombre',
    categorias: ['bermudas'],
    imagenes: [{ src: remeraBasicaImg, alt: 'Bermuda denim' }],
    variantes: [
      {
        id: 'var-bermuda-denim-42',
        barcode: '779015',
        color: 'Azul',
        talle: '42',
        precio: 34900,
        stockDisponible: 5,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-pantalon-chino',
    nombre: 'Pantalon chino',
    slug: 'pantalon-chino',
    marca: 'Equus',
    genero: 'hombre',
    categorias: ['pantalones'],
    imagenes: [{ src: buzoUrbanoImg, alt: 'Pantalon chino' }],
    variantes: [
      {
        id: 'var-pantalon-chino-beige-44',
        barcode: '779016',
        color: 'Beige',
        talle: '44',
        precio: 55900,
        stockDisponible: 3,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-buzo-vans',
    nombre: 'Buzo Vans gris',
    slug: 'buzo-vans-gris',
    marca: 'Vans',
    genero: 'hombre',
    categorias: ['sweaters-y-buzos'],
    imagenes: [{ src: buzoUrbanoImg, alt: 'Buzo Vans gris' }],
    variantes: [
      {
        id: 'var-buzo-gris-xl',
        barcode: '779007',
        color: 'Gris',
        talle: 'XL',
        precio: 52900,
        stockDisponible: 2,
        activo: true,
      },
    ],
  },
  {
    id: 'prod-cinturon-cuero',
    nombre: 'Cinturon cuero',
    slug: 'cinturon-cuero',
    marca: 'Equus',
    genero: 'hombre',
    categorias: ['accesorios'],
    imagenes: [{ src: accesoriosImg, alt: 'Cinturon de cuero' }],
    variantes: [
      {
        id: 'var-cinturon-marron-u',
        barcode: '779008',
        color: 'Marron',
        talle: 'Unico',
        precio: 24900,
        stockDisponible: 8,
        activo: true,
      },
    ],
  },
]
